#DESENVOLVA UM PROGRAMA QUE LEIA QUATRO VALORES PELO TECLADO E GUARDE-OS EM UMA TUPLA. NO FINAL MOSTRE.
#A-QUANTAS VEZES APARECEU O VALOR 9. 
#B-EM QUE POSIÇÃO FOI DIGITADOO PRIMEIRO VLAOR 3. USAR INDEX
#C-QUAIS FORAM OS NÚMEROS PARES