#CRIE UM PROGRAMA QUE LEIA DOIS VALOR E VAI MOSTRAR UM MENU NA TELA 
#[1] SOMAR
#[2] MULTIPLICAR
#[3] MAIOR
#[4] NOVOS NÚMEROS
#[5] SAIR DO PROGRAMA
# SEU PROGRAMA DEVERÁ REALIZAR A OPERAÇÃO SOLICITADA EM CADA CASO. 
valor1 = (int(input('Digite o primeiro valor:')))
valor2 = (int(input('Digite o segundo valor:')))

