a =int(input('digite o valor ')) 
b =int(input('digite o valor '))
print('resutaldo é :',a+b)
print('resutaldo é :',a-b)
print('resutaldo é :',a*b)
print('resutaldo é :',a/b)
print('resutaldo é :',a**b)
print('resutaldo é :',a//b)
print('resutaldo é :',5%2)