#CRIE UMA TUPLA PREENCHIDA COM OS 20 PRIMEIROS COLOCADOS DA TABELA DO CAMPENATO BRASILEIRO DE FUTEBOL
#NA ORDEM DE COLOCAÇÃO. DEPOIS MOSTRE:
#A-APENAS OS 5 PRIMEIROS COLOCADOS
#B-OS 4 ÚLTIMOS COLOCADOS DA TABELA
#C-UM LISTA COM OS TIMES EM ORDEM ALFABÉTICA
#D-EM QUE POSIÇÃO NA TABELA ESTÁ O TIME DA CHAPECOENSE. 
